// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenDriven
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenDriven.4d960ed5-8728-4be3-8261-5619a2b7aa7f";
        public const string Name = "OpenDriven";
        public const string Description = @"Debugging and running of nunit tests in VS2022 (Similar to TestDriven.NET)";
        public const string Language = "en-US";
        public const string Version = "0.13";
        public const string Author = "Ryan De Boer";
        public const string Tags = "";
    }
}
