// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenDriven
{
  internal sealed partial class Vsix
  {
    public const string Id = "OpenDriven.4d960ed5-8728-4be3-8261-5619a2b7aa7f";
    public const string Name = "OpenDriven";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Ryan De Boer";
    public const string Tags = "";
  }
}
