// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenDriven
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenDrivenString = "9fa6c0c7-f9fa-4eec-92e4-cce58209226a";
        public static Guid OpenDriven = new Guid(OpenDrivenString);

        public const string guidOpenDrivenPackageCmdSetString = "c5bccf32-96d1-4e8a-93b2-a9c56ea803d9";
        public static Guid guidOpenDrivenPackageCmdSet = new Guid(guidOpenDrivenPackageCmdSetString);

        public const string guidImagesString = "d65142af-d736-4826-8f66-fb14c9c96117";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "07308648-1c6b-4281-b48d-019867018e0f";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "5073aeb6-8505-4b2c-b192-6d82c83d9029";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "260618dd-2a75-4fcc-9b22-f81799f19273";
        public static Guid guidImages3 = new Guid(guidImages3String);

        public const string guidImages4String = "b5c6b537-5999-408a-8927-8978cd90f42e";
        public static Guid guidImages4 = new Guid(guidImages4String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int EditorContextMenuGroup = 0x1020;
        public const int cmdidCommand1 = 0x0100;
        public const int cmdidDebugCommand = 0x0101;
        public const int cmdidToolbarTestCommand = 0x1021;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int cmdidToolbarCommand2 = 0x1051;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}